### PR TITLE
Improved task detection

### PR DESCRIPTION
**Pull request by domtronn**
I was thinking about ways to improve the task resolution, and I realised we could use `grunt --help` and actually let the executable do the heavy lifting to calculate tasks rather than scrubbing through the `gruntfile.js`!

I updated the `grunt-resolve-registered-tasks` test to use a new `grunt-help.txt` stub data file and assert that the tasks are the ones present in this file.

The main refactor of that function basically runs the `grunt --help` shell command and scrubs through this for a list of available tasks.

### CODE REVIEW

**Comment by gempesaw** [comment]
oh! that sounds like a significantly better idea. and there's passing tests to boot, I'm a happy camper. I'm not at my computer-with-grunt-on-it right now, but I'll take it for a spin tomorrow morning and get this merged in :D

thinking out loud...

- is it noticeably any slower this way, having to shell out each time ? ( hopefully not, i'll find out tomorrow ofc :) 
- hmm, is there a case where `grunt --help` might fail to execute but the grunt tasks could still be run ? ( I can't think how that might happen except for purposefully fiddling with grunt's internals. )
- is there any use in keeping the old method around as a customization option in case someone really likes regexp parsing a js file ? ( i'm leaning towards no )
-

**Comment by domtronn** [comment]
@gempesaw to answer some of those questions,
* Yeah, unfortunately, it is noticeably slower _(did some profiling and the new way takes average `0.56s`, the old way takes `0.00s` :disappointed: )_, but the main slow down is the execution of `grunt --help` itself, and there are ways we could improve this like caching the `grunt --help` response until the current `Gruntfile.js` changes! 
* I considered that but couldn't decide on what `grunt-exec` should do if something goes wrong.
* It might be worth adding in the option, but you'd be switching on whether you want _all_ of the tasks or just the ones you register? Options are always good though, I'll look at adding the old stuff back in and switch on some customisation variable :smile: 

Ultimately though, the slow down's not noticeable, I think I was told once that `0.7s+` is where people start feeling the unresponsiveness!

I might look into the caching thing though and see if I can speed it up. :smile:

**Comment by domtronn** [comment]
I've added in the ability to cache the tasks and added a bunch of tests around the clearing of the tasks cache, which should imply they get served from the cache downstream.

I reran the profiling it dropped from `~0.5s` to `~3.9e-07s` with caching on, so yeah, massive improvement there! :grin:

**Comment by domtronn** [comment]
I've also reintroduced the old method of resolving the tasks which will toggle on a boolean `defcustom`.

I've described it as either loading _all_ of the grunt tasks or _just_ the user registered ones, this seemed to be the proper way to market the toggling as the difference of purpose could be useful for some. :grey_question:

**Comment by gempesaw** [comment]
no problem, the caching you implemented makes a huge difference! :D

just waiting on travis and then this stuff should get into master and out into melpa-unstable. i'll test it out a bit and then tag it at v1.0.0 afterwards for melpa stable. cheers :)

**Comment by gempesaw** [comment]
thanks! :D

**Pull request merged**
